#!/usr/bin/env python3
"""
AI-powered Git commit message generator — one tool, many providers.

This single module replaces the old family of per-provider scripts
(aica.py / aicg.py / aico.py / aicl.py). It generates a conventional-commit
message from your staged changes using whichever AI provider you pick.

Providers (the "implementations" behind one shared framework):
  - Ollama (local)     — no API key, runs at localhost:11434          (--provider ollama)
  - Anthropic Claude   — ANTHROPIC_API_KEY                            (--provider anthropic)
  - Google Gemini      — GOOGLE_API_KEY / GEMINI_API_KEY              (--provider gemini)
  - OpenAI             — OPENAI_API_KEY                               (--provider openai)

Usage:
  git aic                 # auto-detect: Ollama (local) > Anthropic > Gemini > OpenAI
  git aic --cloud         # skip Ollama, use the best available cloud provider
  git aic --provider X    # force a specific provider (X = ollama|anthropic|gemini|openai)

All commit flags work the same across every provider:
  FILES...                stage these files first
  -a / --add-all          stage all changes (git add .)
  -i / --interactive-add  stage interactively via 'git adi' (fzf)
  -d / --dry-run          print the message, do not commit
  -r / --review           review before committing  [y/n/e/r]
  -p / --push             push after a successful commit
  -m / --model            pick the model interactively
  -f / --fill-placeholders   fill the 'cinfo' placeholders for extra context
  -w / --watermark        append a "Generated by ..." signature
  -v / --debug            verbose logging

Design: a `Provider` abstract base class declares the contract; each concrete
provider implements only its own API calls. The shared git framework
(staging, prompt building, the review/commit loop) lives here exactly once.
Third-party SDKs are imported lazily — only the chosen provider's packages are
installed/loaded, so an OpenAI-only user never pulls in the Anthropic SDK.
"""

import os
import sys
import abc
import time
import argparse
import subprocess
import tempfile
import urllib.request
import urllib.error
import msvcrt  # single-character input on Windows (this is a Windows toolbox)

# --- 🛡️ Self-Healing Header ---
try:
    import dependency_manager
except ImportError:
    print("🚨 Critical: 'dependency_manager.py' is missing from this folder.")
    sys.exit(1)

# ---------------------------------------------------------------------------
# Ollama configuration — override any of these via environment variables.
# ---------------------------------------------------------------------------
OLLAMA_BASE_URL    = os.environ.get("OLLAMA_BASE_URL", "http://localhost:11434")
# Context window cap — CRITICAL for RAM control. llama3.1:8b at default 131072
# ctx → ~31 GB RAM; at 8192 → ~6-7 GB. For commit messages 8192 is plenty.
OLLAMA_NUM_CTX     = int(os.environ.get("OLLAMA_NUM_CTX",     "8192"))
OLLAMA_NUM_PREDICT = int(os.environ.get("OLLAMA_NUM_PREDICT", "512"))
OLLAMA_TIMEOUT     = int(os.environ.get("OLLAMA_TIMEOUT",     "60"))
# Max fallback models to try after the primary fails (keeps the failure path fast).
MAX_FALLBACK_MODELS = int(os.environ.get("OLLAMA_MAX_FALLBACKS", "3"))
# Max model size (GB) eligible for automatic fallback (tuned for a 32GB box).
OLLAMA_MAX_MODEL_SIZE = int(os.environ.get("OLLAMA_MAX_MODEL_SIZE_GB", "8")) * (1024 ** 3)

# Preferred Ollama models, ordered QUALITY → SPEED. The auto-picker uses the
# first INSTALLED model here as the primary; automatic fallback still walks the
# installed list SMALLEST-FIRST so a heavy primary failure retries with light ones.
PREFERRED_MODELS = [
    "gemma3:12b",        # 8.1 GB  — high quality, primary default
    "gemma3n:e4b",       # 7.5 GB  — strong alternative
    "llama3.1:8b",       # 4.9 GB  — solid mid-tier
    "gemma3:4b",         # 3.3 GB  — compact, still decent
    "codellama:latest",  # 3.8 GB  — code-aware, reliable
    "llama2:latest",     # 3.8 GB  — older but dependable
    "llama3.2:latest",   # 2.0 GB  — fast fallback
    "llama3.2:3b",       # 2.0 GB  — fast fallback
]

# Shared system prompt used by every provider.
STRICT_INSTRUCTIONS = (
    "You are an expert developer writing a semantic git commit message. "
    "Follow conventional commit format (type: subject). "
    "OUTPUT ONLY the raw commit message. "
    "Do NOT add any markdown formatting (like ```). "
    "Do NOT add any introductory words (like 'Here is the message'). "
    "Start your response DIRECTLY with the commit type (e.g., feat:, fix:, docs:)."
)


# ===========================================================================
# Small shared helpers
# ===========================================================================

def print_status(msg, end='\n'):
    """Print to stderr so it doesn't pollute captured stdout in pipelines."""
    print(msg, file=sys.stderr, flush=True, end=end)


def mask_key(value, show=4):
    """Return a masked secret: first N + *** + last N chars."""
    if not value or len(value) <= show * 2:
        return '***'
    return f"{value[:show]}{'*' * 8}{value[-show:]}"


def _suppress_ssl_warnings():
    """Silence urllib3 InsecureRequestWarning (we use verify=False on Windows)."""
    try:
        import urllib3
        urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
    except Exception:
        pass


def format_size(size_bytes):
    """Convert bytes to a human-readable size string (e.g. '2.0 GB', '621 MB')."""
    if not size_bytes:
        return "? GB"
    gb = size_bytes / (1024 ** 3)
    if gb >= 1.0:
        return f"{gb:.1f} GB"
    mb = size_bytes / (1024 ** 2)
    return f"{mb:.0f} MB"


def is_ollama_available(base_url=None, timeout=2):
    """
    Probe GET /api/tags to check if Ollama is running. Stdlib only (urllib).
    Returns (True, None) on success, or (False, reason_string) on failure.
    """
    base_url = base_url or OLLAMA_BASE_URL
    try:
        req = urllib.request.urlopen(f"{base_url}/api/tags", timeout=timeout)
        return (True, None) if req.status == 200 else (False, f"Ollama returned HTTP {req.status}")
    except urllib.error.HTTPError as e:
        return (False, f"Ollama returned HTTP {e.code}")
    except urllib.error.URLError as e:
        if isinstance(e.reason, ConnectionRefusedError):
            return (False, "Connection refused (Ollama not running?)")
        if isinstance(e.reason, (TimeoutError, OSError)) and 'timed out' in str(e.reason):
            return (False, f"Connection timed out after {timeout}s (Ollama unresponsive?)")
        return (False, f"Network error: {e.reason}")
    except Exception as e:
        return (False, f"Unexpected error: {e}")


def ollama_retry_or_exit(reason, base_url, auto_retries=1):
    """Show why Ollama failed, auto-retry, then return True if it came back."""
    print_status(f"\n⚠️  Ollama: {reason}")
    for attempt in range(1, auto_retries + 1):
        print_status(f"🔄 Retrying Ollama... (attempt {attempt})")
        time.sleep(2)
        ok, reason = is_ollama_available(base_url=base_url)
        if ok:
            print_status("✅ Ollama is back!")
            return True
        print_status(f"⚠️  Ollama: {reason}")
    print_status("   Auto-retry exhausted.")
    print_status("   To use cloud instead: aic --cloud  (or aic -c)")
    print_status("   To fix Ollama: ollama serve  (then re-run aic)")
    return False


# ===========================================================================
# Shared git framework (one copy for every provider)
# ===========================================================================

def run_git_with_ownership_fix(git_command, operation_description="Git operation", debug=False):
    """
    Execute a git command, auto-healing Git's "dubious ownership" error by adding
    the repo to safe.directory and retrying once. Returns the CompletedProcess.
    """
    try:
        result = subprocess.run(git_command, check=True, capture_output=True, text=True)
        if debug:
            print(f"🐛 [DEBUG] Command succeeded: {' '.join(git_command)}")
            if result.stdout:
                print(f"🐛 [DEBUG] stdout: {result.stdout[:500]}")
        return result
    except subprocess.CalledProcessError as e:
        if debug:
            print(f"🐛 [DEBUG] Command failed: {' '.join(git_command)}")
            print(f"🐛 [DEBUG] Exit code: {e.returncode}")
            print(f"🐛 [DEBUG] stderr: {e.stderr}")

        if e.returncode == 128 and 'dubious ownership' in e.stderr:
            print(f"🔧 Detected Git ownership issue during {operation_description}.")
            print("   Configuring repository-local safe.directory...")

            try:
                repo_result = subprocess.run(
                    ['git', 'rev-parse', '--show-toplevel'],
                    capture_output=True, text=True, check=True
                )
                repo_path = repo_result.stdout.strip()
            except subprocess.CalledProcessError:
                print("⚠️ Could not determine repository path. Using current directory.")
                repo_path = os.getcwd()

            try:
                if debug:
                    print(f"🐛 [DEBUG] Adding '{repo_path}' to safe.directory")
                subprocess.run(
                    ['git', 'config', '--global', '--add', 'safe.directory', repo_path],
                    check=True, capture_output=True, text=True
                )
                print(f"✅ Added '{repo_path}' to safe.directory config.")
                print(f"🔄 Retrying {operation_description}...")
                retry_result = subprocess.run(git_command, check=True, capture_output=True, text=True)
                return retry_result
            except subprocess.CalledProcessError as retry_error:
                print(f"🚨 Failed to fix ownership issue: {retry_error}")
                if debug:
                    print(f"🐛 [DEBUG] Retry stderr: {retry_error.stderr}")
                sys.exit(1)
        else:
            print(f"🚨 Error during {operation_description}: {e.stderr}")
            raise


def interactive_add(debug_mode=False):
    """Trigger 'git adi' (interactive fzf staging); show status before and after."""
    print("\n✅ --interactive-add flag detected.")
    print("\n📂 Current Status (Untracked/Modified):")
    try:
        run_git_with_ownership_fix(['git', 'status', '-sb', '-uall'],
                                   operation_description="status check", debug=debug_mode)
    except subprocess.CalledProcessError:
        pass

    print("\n🚀 Launching interactive staging (fzf)...")
    try:
        subprocess.run(['git', 'adi'], capture_output=True, text=True, encoding='utf-8')
        result = subprocess.run(['git', 'diff', '--staged', '--quiet'])
        if result.returncode == 0:
            print("\n🤷 No files were staged. Aborting commit process.")
            sys.exit(0)
        print("\n✅ Staged Changes Summary:")
        subprocess.run(['git', 'diff', '--staged', '--stat'], check=True)
        if debug_mode:
            print("\n🐛 [DEBUG] Full Staged Diff:")
            subprocess.run(['git', '--no-pager', 'diff', '--staged'], check=True)
        print("\n---")
    except FileNotFoundError:
        print("\n🚨 Error: 'git' command not found. Is Git installed and in your PATH?")
        sys.exit(1)
    except Exception as e:
        print(f"\n🚨 An unexpected error occurred during interactive add: {e}")
        sys.exit(1)


def get_prompt_from_git(alias_name):
    """Execute the user's git alias (e.g. 'cinfo') to capture the prompt context."""
    print(f"🤖 Running 'git {alias_name}' to generate prompt...")
    try:
        result = subprocess.run(['git', alias_name], capture_output=True, text=True,
                                check=True, encoding='utf-8')
        print("---")
        return result.stdout.strip()
    except subprocess.CalledProcessError as e:
        if "is not a git command" in (e.stderr or ""):
            print(f"\n🚨 Error: 'git {alias_name}' is not recognized as a git command or alias.")
            print(f"   Make sure the '{alias_name}' alias is configured in your git config.")
            print(f"   You may need to run 'gitinit.cmd' to set up your git aliases.")
            sys.exit(0)
        print(f"\n🚨 Error running 'git {alias_name}': {e.stderr}")
        sys.exit(1)


def make_git_commit(message, dry_run=False, review=False, push=False, add_all=False, can_regenerate=False):
    """Create the git commit, allowing a final review/edit and GPG-failure recovery."""
    if dry_run:
        print("\n✅ --- DRY RUN: COMMIT MESSAGE --- ✅\n" + message + "\n✅ --- END DRY RUN --- ✅\n")
        return

    commit_command = ['git', 'commit', '--no-quiet', '--verbose', '--branch',
                      '--ahead-behind', '--status', '--signoff']
    should_commit = False
    temp_file_name = None

    if review:
        print("\n🔎 --- REVIEW COMMIT MESSAGE --- 🔎\n" + message + "\n---------------------------------\n")
        print("Choose an action:")
        print("  [y] Yes - Commit with this message")
        print("  [n] No - Abort the commit")
        print("  [e] Edit - Open editor to modify the message")
        if can_regenerate:
            print("  [r] Regenerate - Request a new AI-generated message (costs additional API token)")
        print()
        options_text = "(y/n/e/r)" if can_regenerate else "(y/n/e)"
        print(f"Enter your choice {options_text}: ", end='', flush=True)

        key_press = msvcrt.getch()
        try:
            print(key_press.decode('utf-8'))
        except Exception:
            print(str(key_press))

        if key_press.lower() == b'y':
            print("\n👍 Approved. Committing...")
            commit_command.extend(['-m', message])
            should_commit = True
        elif key_press.lower() == b'e':
            print("\n📝 Opening editor to edit the message...")
            with tempfile.NamedTemporaryFile(mode='w+', delete=False, encoding='utf-8') as temp_file:
                temp_file.write(message)
                temp_file_name = temp_file.name
            commit_command.extend(['-e', '-F', temp_file_name])
            should_commit = True
        elif can_regenerate and key_press.lower() == b'r':
            return "REGENERATE"
        else:
            print("\n❌ Aborted by user.")
            if add_all:
                print("\n🧹 --add-all flag was used. Unstaging files to clean up...")
                subprocess.run(['git', 'restore', '--staged', '.'], check=True)
                print("✅ Cleanup complete.")
            sys.exit(0)
    else:
        should_commit = True

    if should_commit:
        if temp_file_name and not any(opt in commit_command for opt in ('-e', '-F', '--file')):
            commit_command.extend(['--file', temp_file_name, '--edit'])
        elif not any(opt in commit_command for opt in ('-m', '--message', '-e', '-F', '--file')):
            commit_command.extend(['-m', message])

        while True:
            try:
                print("\n🚀 Executing commit...")
                subprocess.run(commit_command, check=True, text=True, encoding='utf-8',
                               stderr=subprocess.PIPE)
                if temp_file_name:
                    try:
                        os.unlink(temp_file_name)
                    except Exception:
                        pass
                print("\n✅ Commit successful!")
                try:
                    subprocess.run([
                        'git', '--no-pager', 'log', '-1',
                        '--pretty=format:%C(yellow)%h%Creset %s %C(green)(%ar) %C(bold blue)<%an>%Creset%n%B%n'
                    ], check=True)
                except Exception:
                    pass
                if push:
                    print("\n📤 Pushing to remote...")
                    subprocess.run(['git', 'push', '--verbose', '--progress'], check=True,
                                   text=True, encoding='utf-8')
                    print("✅ Push successful!")
                break
            except subprocess.CalledProcessError as e:
                error_output = (e.stderr or str(e)).lower()
                is_gpg_failure = ('gpg failed to sign' in error_output
                                  or 'failed to write commit object' in error_output)
                if not is_gpg_failure:
                    print(f"\n🚨 Commit failed: {e}")
                    sys.exit(1)

                saved_path = os.path.join('.git', 'COMMIT_MSG_SAVED')
                try:
                    with open(saved_path, 'w', encoding='utf-8') as f:
                        f.write(message)
                except Exception:
                    saved_path = None

                print(f"\n🔐 GPG signing failed. Your commit message is preserved.")
                if saved_path:
                    print(f"   Message saved to: {saved_path}")
                print("\nChoose an action:")
                print("  [r] Retry      - Try committing again (fix GPG in another terminal first)")
                print("  [s] Skip sign  - Commit without GPG signature (--no-gpg-sign)")
                print("  [n] Abort      - Exit (message saved for manual use)")
                print()
                print("Enter your choice (r/s/n): ", end='', flush=True)

                gpg_key = msvcrt.getch()
                try:
                    print(gpg_key.decode('utf-8'))
                except Exception:
                    print(str(gpg_key))

                if gpg_key.lower() == b'r':
                    print("\n🔄 Retrying commit...")
                    continue
                elif gpg_key.lower() == b's':
                    print("\n⚠️  Committing without GPG signature...")
                    if '--no-gpg-sign' not in commit_command:
                        commit_command.append('--no-gpg-sign')
                    continue
                else:
                    print("\n❌ Aborted. Your message is saved.")
                    if saved_path:
                        print(f"   To commit manually: git commit -F {saved_path}")
                    sys.exit(1)


def _clean_message(raw_text, signature=None):
    """Strip markdown/intro artifacts; optionally append a provider signature."""
    clean_text = raw_text.replace("```", "").strip()
    if clean_text.lower().startswith("text:"):
        clean_text = clean_text[5:].strip()
    elif clean_text.lower().startswith("text"):
        clean_text = clean_text[4:].strip()
    if clean_text.lower().startswith("commit message:"):
        clean_text = clean_text[15:].strip()
    if signature:
        clean_text += f"\n\n{signature}"
    return clean_text


# ===========================================================================
# Provider contract (the "interface") + concrete implementations
# ===========================================================================

class OllamaExhausted(Exception):
    """Raised when every local Ollama model fails — caller may offer a cloud switch."""


class Provider(abc.ABC):
    """Abstract base: the contract every AI provider must satisfy."""
    name = "Provider"
    icon = "🤖"
    env_vars = []          # env keys that signal availability (empty for Ollama)
    pip_deps = []          # packages to install lazily for this provider
    default_model = None

    def is_available(self):
        """Default: available if any of its env vars is set."""
        return any(os.environ.get(v) for v in self.env_vars)

    def ensure_deps(self):
        """Install this provider's third-party packages exactly once (lazy)."""
        if getattr(self, '_deps_ready', False):
            return
        if self.pip_deps:
            dependency_manager.require(list(self.pip_deps))
        self._deps_ready = True

    def pick_model(self, interactive):
        """Default model selection: interactive picker, else the provider default."""
        if interactive:
            model = self.select_custom_model()
            print(f"🎯 Using model: {model}\n")
            return model
        return self.default_model

    @abc.abstractmethod
    def make_client(self):
        """Read credentials and build any API client. Imports the SDK lazily."""

    @abc.abstractmethod
    def get_available_models(self):
        """Return the provider's list of usable models."""

    @abc.abstractmethod
    def select_custom_model(self):
        """Interactively pick a model; return its id."""

    @abc.abstractmethod
    def generate_commit_message(self, prompt, include_signature, model_name):
        """Call the provider's API and return a cleaned commit message string."""


class AnthropicProvider(Provider):
    name = "Anthropic Claude"
    icon = "🟠"
    env_vars = ["ANTHROPIC_API_KEY"]
    pip_deps = ["anthropic", "httpx"]
    default_model = "claude-haiku-4-5-20251001"

    def make_client(self):
        import anthropic
        import httpx
        _suppress_ssl_warnings()
        try:
            key = os.environ["ANTHROPIC_API_KEY"]
        except KeyError:
            print("\n🚨 Error: ANTHROPIC_API_KEY environment variable is not set.")
            print("   Please set ANTHROPIC_API_KEY in your environment.")
            print("   Get your API key from: https://console.anthropic.com/")
            sys.exit(1)
        # SSL verification disabled to avoid certificate issues on Windows.
        self.client = anthropic.Anthropic(api_key=key, http_client=httpx.Client(verify=False))

    def get_available_models(self):
        try:
            models_data = self.client.models.list()
            generation_models = [m for m in models_data.data if m.id.startswith('claude-')]
            generation_models.sort(key=lambda x: x.id, reverse=True)
            return generation_models
        except Exception as e:
            print(f"\n🚨 Error fetching models: {e}")
            return []

    def select_custom_model(self):
        print("🔍 Fetching available models for your API key...")
        models = self.get_available_models()
        if not models:
            print("⚠️ Could not fetch models or no Claude models found.")
            print(f"   Falling back to default: {self.default_model}")
            return self.default_model
        print("\n--- 🤖 Available Anthropic Claude Models ---")
        for idx, model in enumerate(models, 1):
            display_name = getattr(model, 'display_name', model.id)
            print(f"  [{idx:2}] {model.id:<45} | {display_name}")
        while True:
            try:
                choice = input(f"\nSelect model [1-{len(models)}] or press Enter for default ({self.default_model}): ").strip()
                if not choice:
                    print(f"✅ Using default: {self.default_model}")
                    return self.default_model
                idx = int(choice) - 1
                if 0 <= idx < len(models):
                    print(f"✅ Selected: {models[idx].id}")
                    return models[idx].id
                print(f"❌ Please enter a number between 1 and {len(models)}")
            except ValueError:
                print("❌ Invalid input. Please enter a number.")
            except KeyboardInterrupt:
                print(f"\n\n⚠️ Selection cancelled. Using default: {self.default_model}")
                return self.default_model

    def generate_commit_message(self, prompt, include_signature, model_name):
        import anthropic
        print(f"✨ Asking {model_name} to generate the commit message...")
        context_input = (f"Analyze the following git context and generate the message.\n\n"
                         f"--- START GIT CONTEXT ---\n{prompt}\n--- END GIT CONTEXT ---")
        try:
            response = self.client.messages.create(
                model=model_name, max_tokens=1024, system=STRICT_INSTRUCTIONS,
                messages=[{"role": "user", "content": context_input}])
            raw_text = response.content[0].text.strip()
            sig = "--Generated by Anthropic Claude." if include_signature else None
            return _clean_message(raw_text, sig)
        except anthropic.RateLimitError:
            print("\n🚨 Rate Limit Exceeded (429 Too Many Requests)")
            print("   You've hit the Anthropic API rate limit.")
            print("\n💡 Solutions:")
            print("   1. Wait a few minutes before trying again")
            print("   2. Check usage/limits at: https://console.anthropic.com/")
            print("   3. Add credits or upgrade your plan if needed")
            sys.exit(1)
        except anthropic.APIError as e:
            print(f"\n🚨 Anthropic API Error: {e}")
            sys.exit(1)
        except anthropic.AnthropicError as e:
            print(f"\n🚨 Anthropic Error: {e}")
            sys.exit(1)
        except Exception as e:
            print(f"\n🚨 An unexpected error occurred: {e}")
            sys.exit(1)


class GeminiProvider(Provider):
    name = "Google Gemini"
    icon = "🔵"
    env_vars = ["GOOGLE_API_KEY", "GEMINI_API_KEY"]
    pip_deps = ["requests"]
    default_model = "gemini-2.0-flash"

    def make_client(self):
        _suppress_ssl_warnings()
        self.api_key = os.environ.get("GOOGLE_API_KEY") or os.environ.get("GEMINI_API_KEY")
        if not self.api_key:
            print("\n🚨 Error: Neither GOOGLE_API_KEY nor GEMINI_API_KEY environment variable is set.")
            print("   Please set GOOGLE_API_KEY (preferred) or GEMINI_API_KEY in your environment.")
            print("   Get your API key from: https://aistudio.google.com/app/apikey")
            sys.exit(1)

    def get_available_models(self):
        import requests
        url = "https://generativelanguage.googleapis.com/v1beta/models"
        headers = {'Content-Type': 'application/json', 'X-goog-api-key': self.api_key}
        try:
            response = requests.get(url, headers=headers, verify=False, timeout=15)
            response.raise_for_status()
            models_data = response.json().get('models', [])
            return [
                m for m in models_data
                if 'generateContent' in m.get('supportedGenerationMethods', [])
                and 'models/' in m['name']
                and not any(x in m['name'] for x in ['embedding', 'aqa', 'text-moderation'])
            ]
        except Exception as e:
            print(f"\n🚨 Error fetching models: {e}")
            return []

    def select_custom_model(self):
        print("🔍 Fetching available models for your API key...")
        models = self.get_available_models()
        if not models:
            print("⚠️ Could not fetch models or no generation models found.")
            print(f"   Falling back to default: {self.default_model}")
            return self.default_model
        print("\n--- 🤖 Available Gemini Models ---")
        for idx, model in enumerate(models, 1):
            model_id = model['name'].replace('models/', '')
            print(f"  [{idx:2}] {model_id:<35} | {model.get('displayName', 'No name')}")
        while True:
            try:
                choice = input(f"\nSelect model [1-{len(models)}] or press Enter for default ({self.default_model}): ").strip()
                if not choice:
                    print(f"✅ Using default: {self.default_model}")
                    return self.default_model
                idx = int(choice) - 1
                if 0 <= idx < len(models):
                    selected = models[idx]['name'].replace('models/', '')
                    print(f"✅ Selected: {selected}")
                    return selected
                print(f"❌ Please enter a number between 1 and {len(models)}.")
            except ValueError:
                print("❌ Invalid input. Please enter a number.")
            except KeyboardInterrupt:
                print(f"\n\n⚠️ Selection cancelled. Using default: {self.default_model}")
                return self.default_model

    def generate_commit_message(self, prompt, include_signature, model_name):
        import requests
        print(f"✨ Asking {model_name} to generate the commit message...")
        strict_prompt = (
            "You are an expert developer writing a semantic git commit message.\n"
            "Analyze the following git context and generate the message.\n"
            "--- START GIT CONTEXT ---\n"
            f"{prompt}\n"
            "--- END GIT CONTEXT ---\n"
            "Instructions:\n"
            "1. Follow conventional commit format (type: subject).\n"
            "2. OUTPUT ONLY the raw commit message.\n"
            "3. Do NOT add any markdown formatting (like ```).\n"
            "4. Do NOT add any introductory words (like 'Here is the message' or 'text').\n"
            "5. Start your response DIRECTLY with the commit type (e.g., feat:, fix:, docs:)."
        )
        url = f"https://generativelanguage.googleapis.com/v1beta/models/{model_name}:generateContent"
        headers = {'Content-Type': 'application/json', 'X-goog-api-key': self.api_key}
        data = {"contents": [{"parts": [{"text": strict_prompt}]}]}
        try:
            response = requests.post(url, headers=headers, json=data, verify=False, timeout=30)
            response.raise_for_status()
            json_response = response.json()
            if 'candidates' in json_response and json_response['candidates']:
                raw_text = json_response['candidates'][0]['content']['parts'][0]['text']
                sig = "--Generated by Google Gemini." if include_signature else None
                return _clean_message(raw_text, sig)
            print("\n🚨 API Error: No content candidates found.")
            sys.exit(1)
        except requests.exceptions.HTTPError as e:
            if e.response.status_code == 429:
                print("\n🚨 Rate Limit Exceeded (429 Too Many Requests)")
                print("   You've hit the Gemini API rate limit.")
                print("\n💡 Solutions:")
                print("   1. Wait a few minutes before trying again")
                print("   2. Check your quota at: https://aistudio.google.com/app/apikey")
                print("   3. Consider upgrading to a paid plan for higher limits")
                sys.exit(1)
            print(f"\n🚨 HTTP Error {e.response.status_code}: {e.response.text}")
            sys.exit(1)
        except requests.exceptions.RequestException as e:
            print(f"\n🚨 Network error occurred: {e}")
            print("   Check your internet connection and try again.")
            sys.exit(1)
        except Exception as e:
            print(f"\n🚨 An unexpected error occurred with the Gemini API: {e}")
            sys.exit(1)


class OpenAIProvider(Provider):
    name = "OpenAI"
    icon = "🟢"
    env_vars = ["OPENAI_API_KEY"]
    pip_deps = ["openai", "httpx"]
    default_model = "gpt-5"

    def make_client(self):
        from openai import OpenAI
        import httpx
        _suppress_ssl_warnings()
        try:
            key = os.environ["OPENAI_API_KEY"]
        except KeyError:
            print("\n🚨 Error: OPENAI_API_KEY environment variable is not set.")
            print("   Please set OPENAI_API_KEY in your environment.")
            print("   Get your API key from: https://platform.openai.com/api-keys")
            sys.exit(1)
        # SSL verification disabled to avoid certificate issues on Windows.
        self.client = OpenAI(api_key=key, http_client=httpx.Client(verify=False))

    def get_available_models(self):
        try:
            models_data = self.client.models.list()
            generation_models = [
                m for m in models_data.data
                if any(prefix in m.id for prefix in ['gpt-', 'o1-', 'o3-'])
                and not any(x in m.id for x in ['whisper', 'tts', 'dall-e', 'embedding'])
            ]
            generation_models.sort(key=lambda x: x.id, reverse=True)
            return generation_models
        except Exception as e:
            print(f"\n🚨 Error fetching models: {e}")
            return []

    def select_custom_model(self):
        print("🔍 Fetching available models for your API key...")
        models = self.get_available_models()
        if not models:
            print("⚠️ Could not fetch models or no generation models found.")
            print(f"   Falling back to default: {self.default_model}")
            return self.default_model
        print("\n--- 🤖 Available OpenAI Models ---")
        for idx, model in enumerate(models, 1):
            created = model.created if hasattr(model, 'created') else 'N/A'
            print(f"  [{idx:2}] {model.id:<30} | Created: {created}")
        while True:
            try:
                choice = input(f"\nSelect model [1-{len(models)}] or press Enter for default ({self.default_model}): ").strip()
                if not choice:
                    print(f"✅ Using default: {self.default_model}")
                    return self.default_model
                idx = int(choice) - 1
                if 0 <= idx < len(models):
                    print(f"✅ Selected: {models[idx].id}")
                    return models[idx].id
                print(f"❌ Please enter a number between 1 and {len(models)}")
            except ValueError:
                print("❌ Invalid input. Please enter a number.")
            except KeyboardInterrupt:
                print(f"\n\n⚠️ Selection cancelled. Using default: {self.default_model}")
                return self.default_model

    def choose_low_cost_model(self):
        """Heuristic: prefer mini/fast, then 4o, then any non-pro/non-5; fallback gpt-5."""
        try:
            ids = [m.id for m in self.get_available_models()]
            for kw in ('mini', 'fast'):
                for m in ids:
                    lid = m.lower()
                    if kw in lid and 'pro' not in lid and '5' not in lid:
                        return m
            for m in ids:
                lid = m.lower()
                if '4o' in lid and 'pro' not in lid:
                    return m
            for m in ids:
                lid = m.lower()
                if 'pro' not in lid and '5' not in lid:
                    return m
        except Exception:
            pass
        return 'gpt-5'

    def pick_model(self, interactive):
        if interactive:
            model = self.select_custom_model()
            print(f"🎯 Using model: {model}\n")
            return model
        return self.choose_low_cost_model()

    def generate_commit_message(self, prompt, include_signature, model_name):
        from openai import OpenAIError, APIError, RateLimitError
        print(f"✨ Asking {model_name} to generate the commit message...")
        context_input = (f"Analyze the following git context and generate the message.\n\n"
                         f"--- START GIT CONTEXT ---\n{prompt}\n--- END GIT CONTEXT ---")
        try:
            response = self.client.responses.create(
                model=model_name, instructions=STRICT_INSTRUCTIONS, input=context_input)
            if hasattr(response, 'output_text') and response.output_text:
                raw_text = response.output_text.strip()
            elif hasattr(response, 'output') and response.output:
                text_parts = []
                for item in response.output:
                    if hasattr(item, 'content'):
                        for content_part in item.content:
                            if hasattr(content_part, 'text'):
                                text_parts.append(content_part.text)
                raw_text = '\n'.join(text_parts).strip()
            else:
                print("\n🚨 API Error: No content found in response.")
                sys.exit(1)
            sig = "--Generated by OpenAI." if include_signature else None
            return _clean_message(raw_text, sig)
        except RateLimitError:
            print("\n🚨 Rate Limit Exceeded (429 Too Many Requests)")
            print("   You've hit the OpenAI API rate limit.")
            print("\n💡 Solutions:")
            print("   1. Wait a few minutes before trying again")
            print("   2. Check usage/limits at: https://platform.openai.com/usage")
            print("   3. Add credits or upgrade your plan if needed")
            sys.exit(1)
        except APIError as e:
            print(f"\n🚨 OpenAI API Error: {e}")
            sys.exit(1)
        except OpenAIError as e:
            print(f"\n🚨 OpenAI Error: {e}")
            sys.exit(1)
        except Exception as e:
            print(f"\n🚨 An unexpected error occurred: {e}")
            sys.exit(1)


class OllamaProvider(Provider):
    name = "Ollama (local)"
    icon = "🟣"
    env_vars = []          # no API key — availability is a localhost probe
    pip_deps = ["requests"]
    default_model = "gemma3:12b"

    def is_available(self):
        return is_ollama_available()[0]

    def make_client(self):
        # Startup validation: confirm Ollama is reachable and has models installed.
        _suppress_ssl_warnings()
        available = self.get_available_models()
        if available is None:
            print(f"\n🚨 Error: Ollama is not running at {OLLAMA_BASE_URL}")
            print("   Start Ollama first: run 'ollama serve' or launch the Ollama app, then retry.")
            sys.exit(1)
        if not available:
            print("\n🚨 Error: Ollama is running but has no models installed.")
            print("   Install one, e.g.: ollama pull llama3.2:3b")
            sys.exit(1)
        self._available = available
        self._names = [m["name"] for m in available]
        self._sizes = {m["name"]: m["size_str"] for m in available}
        self._fallback_chain = []

    def get_available_models(self):
        """None = Ollama not running; [] = running but empty; list[dict] otherwise."""
        import requests
        url = f"{OLLAMA_BASE_URL}/api/tags"
        try:
            response = requests.get(url, timeout=5)
            response.raise_for_status()
            models_data = response.json().get("models", [])
            return [{"name": m["name"], "size_bytes": m.get("size", 0),
                     "size_str": format_size(m.get("size", 0))} for m in models_data]
        except requests.exceptions.ConnectionError:
            return None
        except Exception as e:
            print(f"\n🚨 Error fetching Ollama models: {e}")
            return []

    def select_custom_model(self):
        available = self._available
        auto_pick = next((m for m in PREFERRED_MODELS if m in self._names), self._names[0])
        auto_size = self._sizes.get(auto_pick, "?")
        print(f"\n--- 🤖 Available Ollama Models ({len(available)}) ---")
        for idx, m in enumerate(available, 1):
            marker = "  ⭐ preferred" if m["name"] in PREFERRED_MODELS else ""
            print(f"  [{idx:2}] {m['name']:<40} {m['size_str']:>8}{marker}")
        while True:
            try:
                choice = input(f"\nSelect model [1-{len(available)}] or press Enter for auto ({auto_pick}, {auto_size}): ").strip()
                if not choice:
                    print(f"✅ Using: {auto_pick} ({auto_size})")
                    return auto_pick
                idx = int(choice) - 1
                if 0 <= idx < len(available):
                    sel = available[idx]
                    print(f"✅ Selected: {sel['name']} ({sel['size_str']})")
                    return sel["name"]
                print(f"❌ Please enter a number between 1 and {len(available)}")
            except ValueError:
                print("❌ Invalid input. Please enter a number.")
            except KeyboardInterrupt:
                print(f"\n\n⚠️ Selection cancelled. Using: {auto_pick} ({auto_size})")
                return auto_pick

    def pick_model(self, interactive):
        if interactive:
            target = self.select_custom_model()
            print(f"🎯 Using model: {target} ({self._sizes.get(target, '?')})\n")
        else:
            target = next((m for m in PREFERRED_MODELS if m in self._names), self._names[0])
            size = self._sizes.get(target, "?")
            if target not in PREFERRED_MODELS:
                print(f"⚠️  None of the preferred models found. Using first available: {target} ({size})")
            print(f"🤖 Using model: {target} ({size}) (Ollama local)\n")
        # Build the fallback chain: local-only models, sorted small→large, filtered & capped.
        self._fallback_chain = [
            m["name"]
            for m in sorted(
                [m for m in self._available
                 if m["name"] != target
                 and m["size_bytes"] > 0
                 and ":cloud" not in m["name"].lower()
                 and "embed" not in m["name"].lower()
                 and m["size_bytes"] <= OLLAMA_MAX_MODEL_SIZE],
                key=lambda m: m["size_bytes"])
        ][:MAX_FALLBACK_MODELS]
        return target

    def generate_commit_message(self, prompt, include_signature, model_name):
        """Ollama /api/chat with a smart fallback chain. Raises OllamaExhausted when
        every model fails, so the caller can offer a cloud switch."""
        import requests
        context_input = ("Analyze the following git context and generate the message.\n\n"
                         "--- START GIT CONTEXT ---\n"
                         f"{prompt}\n"
                         "--- END GIT CONTEXT ---")
        models_to_try = [model_name]
        models_to_try.extend(m for m in self._fallback_chain if m != model_name)
        url = f"{OLLAMA_BASE_URL}/api/chat"

        for attempt_idx, current_model in enumerate(models_to_try):
            size_str = self._sizes.get(current_model, "")
            size_display = f" ({size_str})" if size_str else ""
            if attempt_idx > 0:
                print(f"🔄 Trying next model: {current_model}{size_display}")
            print(f"✨ Asking {current_model}{size_display} (Ollama local) to generate the commit message...")
            print(f"   [ctx={OLLAMA_NUM_CTX} tokens | timeout={OLLAMA_TIMEOUT}s]")

            payload = {
                "model": current_model,
                "messages": [
                    {"role": "system", "content": STRICT_INSTRUCTIONS},
                    {"role": "user", "content": context_input},
                ],
                "stream": False,
                "options": {"num_ctx": OLLAMA_NUM_CTX, "num_predict": OLLAMA_NUM_PREDICT},
            }
            has_more = attempt_idx < len(models_to_try) - 1

            try:
                response = requests.post(url, json=payload, timeout=OLLAMA_TIMEOUT)
                response.raise_for_status()
                raw_text = response.json()["message"]["content"].strip()
                sig = "--Generated by Ollama (local)." if include_signature else None
                return _clean_message(raw_text, sig)

            except requests.exceptions.Timeout:
                print(f"\n⚠️  {current_model} timed out after {OLLAMA_TIMEOUT}s (RAM may be full or model still loading).")
                if has_more:
                    print("   Cancelling request and trying a smaller model...")
                    continue
                print("\n🚨 All models timed out. Cannot generate commit message.")
                print("   Tip: increase timeout with OLLAMA_TIMEOUT=120 or stop other apps to free RAM.")
                raise OllamaExhausted("all models timed out")

            except requests.exceptions.ConnectionError:
                print("\n⚠️  Connection to Ollama lost (model may have crashed or been evicted from RAM).")
                if has_more:
                    print("   Trying a smaller model...")
                    continue
                print("\n🚨 Ollama is not responding. Cannot generate commit message.")
                print("   Try running 'ollama serve' to restart the service.")
                raise OllamaExhausted("connection lost")

            except requests.exceptions.HTTPError as e:
                status = e.response.status_code
                if status in (500, 503):
                    print(f"\n⚠️  {current_model} returned server error {status} (possible OOM or load failure).")
                    if has_more:
                        print("   Trying a smaller model...")
                        continue
                    print("\n🚨 All models returned server errors.")
                    raise OllamaExhausted(f"server error {status}")
                elif status == 403:
                    print(f"\n⚠️  {current_model} returned 403 Forbidden (cloud model or access denied).")
                    if has_more:
                        print("   Skipping to next model...")
                        continue
                    print("\n🚨 All models exhausted (last was 403 Forbidden).")
                    raise OllamaExhausted("403 Forbidden")
                elif status == 404:
                    print(f"\n⚠️  Model '{current_model}' not found in Ollama.")
                    if has_more:
                        print("   Trying next available model...")
                        continue
                    print("\n🚨 No usable models found.")
                    print("   Install one with: ollama pull llama3.2:3b")
                    raise OllamaExhausted("no usable models")
                else:
                    print(f"\n🚨 HTTP Error {status}: {e.response.text}")
                    sys.exit(1)

            except (KeyError, ValueError) as e:
                print(f"\n🚨 Error parsing Ollama response: {e}")
                try:
                    print(f"   Raw response: {response.text[:300]}")
                except Exception:
                    pass
                sys.exit(1)

            except Exception as e:
                print(f"\n🚨 An unexpected error occurred: {e}")
                sys.exit(1)

        raise OllamaExhausted("all models exhausted")


# ===========================================================================
# Registry / factory + dispatch
# ===========================================================================

PROVIDERS = {
    "ollama":    OllamaProvider,
    "anthropic": AnthropicProvider,
    "gemini":    GeminiProvider,
    "openai":    OpenAIProvider,
}
# Cloud auto-detect order (Ollama is handled first/separately unless --cloud).
CLOUD_ORDER = ["anthropic", "gemini", "openai"]


def get_provider(name):
    """Factory: instantiate a provider by registry name."""
    return PROVIDERS[name]()


def detect_cloud_provider():
    """Return the first cloud provider with credentials set, else None."""
    for key in CLOUD_ORDER:
        provider = get_provider(key)
        if provider.is_available():
            return provider
    return None


def resolve_provider(args):
    """Pick a provider from --provider, or auto-detect (Ollama-first unless --cloud)."""
    if args.provider:
        return get_provider(args.provider)

    if not args.cloud:
        # Ollama-first: it must be reachable in auto mode (use --cloud to skip it).
        ok, reason = is_ollama_available()
        if not ok:
            if not ollama_retry_or_exit(reason, OLLAMA_BASE_URL):
                sys.exit(1)
        return OllamaProvider()

    cloud = detect_cloud_provider()
    if not cloud:
        print_status("\n🚨 No AI provider available.")
        print_status("   --cloud mode is active (Ollama bypassed).")
        print_status("   Set one of the following environment variables:")
        print_status("   • ANTHROPIC_API_KEY  — Anthropic Claude")
        print_status("   • GOOGLE_API_KEY or GEMINI_API_KEY  — Google Gemini")
        print_status("   • OPENAI_API_KEY  — OpenAI")
        sys.exit(1)
    return cloud


def switch_to_cloud_or_exit(reason):
    """Offer to switch to a cloud provider after Ollama exhaustion (msvcrt y/n)."""
    cloud = detect_cloud_provider()
    if cloud:
        print_status("\n⚠️  All local Ollama models exhausted.")
        print_status(f"   Cloud provider available: {cloud.name}")
        print_status(f"   Switch to {cloud.name}? [y/n]: ", end='')
        try:
            key = msvcrt.getch()
            print_status(key.decode('utf-8', errors='replace'))
        except Exception:
            key = b'n'
        if key.lower() == b'y':
            return cloud
        print_status("\n❌ Aborted.")
        print_status("   Tip: use 'aic --cloud' or 'aic -c' to skip Ollama next time.")
        sys.exit(2)
    else:
        print_status("\n🚨 All local models exhausted and no cloud API keys configured.")
        print_status("   Option 1: increase timeout — OLLAMA_TIMEOUT=120 git aic")
        print_status("   Option 2: pick a model manually — git aic -m")
        print_status("   Option 3: set a cloud API key:")
        print_status("     • ANTHROPIC_API_KEY  — Anthropic Claude")
        print_status("     • GOOGLE_API_KEY     — Google Gemini")
        print_status("     • OPENAI_API_KEY     — OpenAI")
        sys.exit(2)


def announce_provider(provider, args):
    """One stderr line naming the chosen provider (verbose adds masked key)."""
    if args.debug:
        print_status(f"🤖 [aic] Provider : {provider.icon} {provider.name}")
        for v in provider.env_vars:
            if os.environ.get(v):
                print_status(f"🤖 [aic] Key var  : {v} = {mask_key(os.environ[v])}")
                break
    else:
        print_status(f"🤖 via {provider.name}")


# ===========================================================================
# Argument parsing + main run loop
# ===========================================================================

def build_arg_parser():
    epilog_text = """
Examples:
  git aic              auto-detect provider, then commit staged changes
  git aic -r           review the AI message before committing  (y/n/e/r)
  git aic -ap          stage all, commit, then push  (the "one-shot")
  git aic --cloud -r   skip Ollama, use a cloud provider, then review
  git aic --provider openai -m    force OpenAI and pick the model interactively
    """
    parser = argparse.ArgumentParser(
        description="Generate and execute a git commit using an AI provider.",
        epilog=epilog_text, formatter_class=argparse.RawTextHelpFormatter)

    parser.add_argument('files', metavar='FILES', nargs='*',
                        help="Specific files to add/stage automatically.")

    arg_specs = [
        (['-a', '--add-all'], {'action': 'store_true', 'help': "Stage all changes before committing (git add .)."}),
        (['-aa'], {'action': 'store_true', 'help': argparse.SUPPRESS}),
        (['-c', '--cloud'], {'action': 'store_true', 'help': "Skip Ollama; use the best available cloud provider."}),
        (['-d', '-n', '--dry-run'], {'action': 'store_true', 'help': "Print message without committing."}),
        (['-f', '--fill-placeholders'], {'action': 'store_true', 'help': "Prompt to fill placeholders in the cinfo prompt for additional context."}),
        (['-i', '--interactive-add'], {'action': 'store_true', 'help': "Interactively stage files using 'git adi' (fzf)."}),
        (['-m', '--model'], {'action': 'store_true', 'help': "Interactively select a model from the provider's list."}),
        (['-p', '--push'], {'action': 'store_true', 'help': "Push after a successful commit."}),
        (['--provider'], {'choices': list(PROVIDERS), 'help': "Force a provider (ollama|anthropic|gemini|openai)."}),
        (['-r', '--review'], {'action': 'store_true', 'help': "Review message before committing [y/n/e/r]."}),
        (['-v', '--debug'], {'action': 'store_true', 'help': "Enable verbose logging."}),
        (['-w', '--watermark'], {'action': 'store_true', 'help': "Add a 'Generated by ...' signature to the commit message."}),
    ]
    arg_specs.sort(key=lambda x: next((opt for opt in x[0] if opt.startswith('--')), x[0][0]))
    for flags, kwargs in arg_specs:
        parser.add_argument(*flags, **kwargs)
    return parser


def _fill_placeholders(prompt):
    """Show the 'commitplaceholders' alias output and append any values the user enters."""
    print("\n📝 Placeholders for additional context:")
    try:
        result = subprocess.run(['git', 'commitplaceholders'], capture_output=True, text=True, check=True)
        placeholders_output = result.stdout
        print(placeholders_output.strip())
        placeholders = []
        in_section = False
        for line in placeholders_output.split('\n'):
            if line.startswith('## Placeholders for Manual Input:'):
                in_section = True
                continue
            if in_section and line.strip().endswith(':') and not line.startswith('##'):
                placeholders.append(line.strip())
    except subprocess.CalledProcessError as e:
        print(f"🚨 Error displaying placeholders: {e}")
        placeholders = []

    if placeholders:
        filled_values = {}
        print("\nEnter values for each placeholder (press Enter to skip):")
        for ph in placeholders:
            value = input(f"{ph} ").strip()
            if value:
                filled_values[ph] = value
        if filled_values:
            prompt += "\n\n## Filled Placeholders:"
            for ph, val in filled_values.items():
                prompt += f"\n{ph} {val}"
    return prompt


def _commit_with_regeneration(provider, target_model, prompt, args):
    """Generate → review/commit loop, with cloud fallback on Ollama exhaustion."""
    MAX_RETRIES = 2
    attempt = 0
    while attempt <= MAX_RETRIES:
        try:
            commit_message = provider.generate_commit_message(
                prompt, include_signature=args.watermark, model_name=target_model)
        except OllamaExhausted as e:
            provider = switch_to_cloud_or_exit(str(e))
            announce_provider(provider, args)
            provider.ensure_deps()
            provider.make_client()
            target_model = provider.pick_model(interactive=args.model)
            continue  # regenerate with the cloud provider (attempt count unchanged)

        result = make_git_commit(
            commit_message, dry_run=args.dry_run, review=args.review, push=args.push,
            add_all=(args.add_all or args.aa), can_regenerate=(attempt < MAX_RETRIES))

        if result == "REGENERATE":
            attempt += 1
            if attempt <= MAX_RETRIES:
                print(f"\n🔄 Regeneration requested (attempt {attempt}/{MAX_RETRIES})...")
            else:
                print(f"\n⚠️ Maximum regeneration attempts ({MAX_RETRIES}) reached.")
                print("   Using the last generated message.")
                make_git_commit(
                    commit_message, dry_run=args.dry_run, review=False, push=args.push,
                    add_all=(args.add_all or args.aa), can_regenerate=False)
                break
        else:
            break


def run(argv):
    args = build_arg_parser().parse_args(argv)

    # --- Provider resolution + lazy setup ---
    provider = resolve_provider(args)
    announce_provider(provider, args)
    provider.ensure_deps()
    provider.make_client()
    target_model = provider.pick_model(interactive=args.model)

    # --- Interactive staging ---
    if args.interactive_add:
        interactive_add(debug_mode=args.debug)

    # --- Stage specific files ---
    if args.files:
        print(f"📂 Staging specified files: {', '.join(args.files)}")
        for file in args.files:
            print(f"   ➕ Adding: {file}")
            try:
                run_git_with_ownership_fix(['git', 'add', file],
                                           operation_description=f"staging {file}", debug=args.debug)
            except subprocess.CalledProcessError:
                print(f"\n🚨 Failed to stage file: {file}")
                sys.exit(1)
        print("✅ File staging complete.\n")

    # --- Stage everything ---
    if args.add_all or args.aa:
        print("\n✅ --add-all flag detected. Staging all changes...")
        try:
            run_git_with_ownership_fix(['git', 'add', '.', '-v'],
                                       operation_description="staging all changes", debug=args.debug)
            print("---")
        except subprocess.CalledProcessError as e:
            print(f"\n🚨 Failed to stage changes: {e}")
            sys.exit(1)

    # --- Nothing staged? stop. ---
    if subprocess.run(['git', 'diff', '--staged', '--quiet']).returncode == 0:
        print("\n🤷 No changes staged for commit. Use 'git add' or pass filenames to this script.")
        sys.exit(0)

    # --- Build the prompt from 'git cinfo' (+ optional placeholders) ---
    prompt = get_prompt_from_git('cinfo')
    if args.fill_placeholders:
        prompt = _fill_placeholders(prompt)

    if args.debug:
        print("\n🐛 [DEBUG] Generated Prompt Preview:")
        print(f"{prompt[:500]}...\n" if len(prompt) > 500 else f"{prompt}\n")
        if getattr(provider, '_fallback_chain', None):
            print(f"🐛 [DEBUG] Fallback chain: {provider._fallback_chain}\n")

    # --- Generate + commit (with regeneration + cloud fallback) ---
    _commit_with_regeneration(provider, target_model, prompt, args)

    # --- Cleanup for the safe-preview combo ---
    if (args.add_all or args.aa) and args.dry_run:
        print("\n🧹 --add-all and --dry-run detected. Unstaging files to clean up...")
        subprocess.run(['git', 'restore', '--staged', '.'], check=True)
        print("✅ Cleanup complete. Staging area is clean.")


if __name__ == "__main__":
    run(sys.argv[1:])
